### ISSUE TITLE
 Could you provide dataset_conversion for Task046_AbdOrgSegm2 Task018_PelvicOrganSegmentation Task051_StructSeg2019_Task3_Thoracic_OAR

### ISSUE THREAD

**Issue by joelive** [MIC-DKFZ/MultiTalent#1]
Could you provide dataset_conversion for Task046_AbdOrgSegm2 Task018_PelvicOrganSegmentation Task051_StructSeg2019_Task3_Thoracic_OAR?
[NIH-Pan](https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT) seems download as dicom format, while the correspondent dataset_conversion seems accept .nii.gz files only. Could update the dataset_conversion?

**Comment by constantinulrich** [comment]
Hi, sorry for the late reply. I was on vacation after the Miccai. 
I added the dataset conversion scripts. 
We used the data that was already converted years ago, so let me know if it works...

**Comment by constantinulrich** [comment]
Working on it. Sorry for the late reply. I was on vacation after Miccai. 
We used the data from our drives that were already converted back then. I added the Task46 and Task51 conversion and adapted the Task62 conversion. Hope everything works. Let me know if it doesn't... 

I will add the task18 conversion scrips soon.
Best
Constantin

**Comment by constantinulrich** [comment]
Task18 dataset conversion is included now. Note that the ground truth annotations are really bad...
