### ISSUE TITLE
Question about Pretrained MultiTalent Model's Handling of Lung/Lung Tumor Labels

### ISSUE THREAD

**Issue by Awayah** [MIC-DKFZ/MultiTalent#11]
HI, I recently ran inference on a lung tumor dataset using the pretrained MultiTalent model. Overall, the performance on the labeled tumor data `06_lungnodule` was promising.

However, when I was examining left and right lung tissue segmentation outputs, (`51_left_lung`, `51_right_lung`)  I observed the presence of 'holes' in the segmentation corresponding to the tumor regions, particularly noticeable with larger tumors. My question is whether the original dataset used for training (specifically Dataset ID: 51) included labeled lung tissue with or without the pathology.

I haven't been able to get access to the relevant dataset used for pretraining (ID: 51), so I would greatly appreciate clarification on it.

Thank you,
Awayah

Example:

<img width="751" alt="image" src="https://github.com/MIC-DKFZ/MultiTalent/assets/138879962/df3f4265-015f-4658-9aca-d7c2313145bb">

**Comment by constantinulrich** [comment]
Hi,  dataset 51 originates from the [structsec](https://structseg2019.grand-challenge.org/) challenge (task3) that is about the segmentation of organs at risk. Therefore, I assume that they did not include the target tumors in the segmentation masks of the OAR...

**Comment by constantinulrich** [comment]
I checked one of the training images: They exclude the tumor...
![image](https://github.com/MIC-DKFZ/MultiTalent/assets/82217013/a56ac287-f5cd-4d4c-a432-cd0975d0efb7)

**Comment by Awayah** [comment]
Thank you for verifying!
