### ISSUE TITLE
single GPU training

### ISSUE THREAD

**Issue by Astarakee** [MIC-DKFZ/MultiTalent#3]
First of all, thanks a lot for open-sourcing this fantastic work.
As the current training procedure is designed to work with DDP, I am wondering whether the training protocols for machines with a single GPU will be released/applicable to this work?
Many thanks in advance,

**Comment by constantinulrich** [comment]
Hi, both inference and fine-tuning using the existing models should work on single GPUs. 
Only the training does not work on single GPUs so far. 

In the last few days we have switched to nnunetv2. There, switching between single GPU and ddp training is much easier. At the same time, we are also working on a more native integration and more flexible training with any data sets. Unfortunately, I can't promise when the update will be available.

**Comment by Astarakee** [comment]
Thank you very much for the quick reply.
