### ISSUE TITLE
Cannot find Trainer when predicting with open source pre-trained model.

### ISSUE THREAD

**Issue by LiangDazhu** [MIC-DKFZ/MultiTalent#4]
Hello, first of all, thank you for your excellent open source project, it helped me a lot. I encountered the following problem when using MultiTalent and I hope you can answer it. After downloading your open source pre-trained model, I got an error when predicting data: ‘RuntimeError: Could not find the model trainer specified in checkpoint in nnunet.trainig.network_training. If it is not located there, please move it or change the code of restore_model. Your model trainer can be located in any directory within nnunet.trainig.network_training (search is recursive).’ I looked at the code and this Trainer might be in the meddec package, but this package is your private one, so I can’t predict. Could you please tell me if there is an open source plan for this nnUNetTrainerV2_leBFnnUNet4_regions_forceBD_DDP_customSplit_sqrtDSSampling_2000epochs corresponding Trainer, so that I can continue to use this model to predict, thank you!

**Comment by constantinulrich** [comment]
Hi, "nnUNetTrainerV2_leBFnnUNet4_regions_forceBD_DDP_customSplit_sqrtDSSampling_2000epochs" was an internal name and should not be used anymore. Could you give me your full error message and the command you used?

**Comment by LiangDazhu** [comment]
Thank you very much for your answer. I downloaded the pre-trained model directly from “https://zenodo.org/record/8297767/files/Task100_MultiTalent.zip?download=1”. I just checked and found that the nnUNet_download_pretrained_model command will modify the downloaded file content. I’ll try again.

**Comment by constantinulrich** [comment]
Yeah sorry for that. I couldn't change the uploaded files afterward.
