### ISSUE TITLE
How to prepare our own multi-dataset for training the MultiTalent?

### ISSUE THREAD

**Issue by ZhangxinruBIT** [MIC-DKFZ/MultiTalent#5]
I want to express my appreciation for the remarkable work on MultiTalent and nnUNet. I have a question about preparing our custom multi-dataset for MultiTalent.

Upon reviewing your paper, it's mentioned that each dataset with each class annotation is treated as a distinct label. My question is, can I manually achieve this step (also make sure the right folder structure of nnUNet is required) and skip the process outlined in "/nnunet/dataset_conversion/Task100_MultiTalent.py"?  Since my own dataset is quite different from yours. Is it feasible to move on to the next step in the process?

I look forward to your guidance on this matter.

**Comment by constantinulrich** [comment]
Hi, you would need to adapt multiple parts of the code, but in general, it is feasible. If your dataset comes from different sources, 
 you probably have different classes for lets say label 1 (eg. label one belongs to class liver in dataset A and to class kidney in dataset 2).  You would need to map them to individual labels as i did in /nnunet/dataset_conversion/Task100_MultiTalent.py

**Comment by ZhangxinruBIT** [comment]
> Hi, you would need to adapt multiple parts of the code, but in general, it is feasible. If your dataset comes from different sources, you probably have different classes for lets say label 1 (eg. label one belongs to class liver in dataset A and to class kidney in dataset 2). You would need to map them to individual labels as i did in /nnunet/dataset_conversion/Task100_MultiTalent.py

Thanks, I think it works now.
