### ISSUE TITLE
About BTCV pre-processing?

### ISSUE THREAD

**Issue by Luffy03** [MIC-DKFZ/MultiTalent#6]
Hello, many thanks for your excellent work first!
I am concerned about the pre-processing process of BTCV. Why the spacing is set to [3.0, 0.76, 0.76]? It is very different from other papers.

**Comment by constantinulrich** [comment]
Hi, thats just the median spacing of the dataset (which is used by default nnunet as target spacing). I used for all MultiTalent experiments a fixed spacing of [1.5,1,1]

**Comment by Luffy03** [comment]
Thanks a lot! I will try it.
